export const SET_ACTIVE_USER_INFO = 'SET_ACTIVE_USER_INFO';
export const CLEAR_ACTIVE_USER_INFO = 'CLEAR_ACTIVE_USER_INFO';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const CLEAR_USER_POSTS = 'CLEAR_USER_POSTS';
export const ADD_NEW_POST = 'ADD_NEW_POST';
